[package]
name = "desktop"
version = "0.0.0"
edition = "2021"

[lib]
name = "desktop_lib"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "desktop"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2", features = ["shell-open"] }

[build-dependencies]
tauri-build = { version = "2" }
